### ISSUE TITLE
You guys have patreon?

### ISSUE THREAD

**Issue by johhansantana** [Sly777/ran#342]
First of all, thank you for creating this awesome library.

I really want to contribute but I have no time at the moment, the only way I can think of is using patreon for helping keep this library alive. 

Do you guys have planned on creating this or have some other donation options?

**Comment by Sly777** [comment]
Hey @johhansantana!

Thanks so much to think like this. Honestly, I just opened it on open collective (https://opencollective.com/ran). I think Patreon is a little bit complicated for people who are living in non-US (Germany). Also, I'm really newbie on these patreon, open collective and similar websites :)

But I need to think detailed about this because I didn't do this to make money actually. So It can be useful if I can donate to charity with the project name. But I need to search for this first :)

p.s.: Happy new year!

**Comment by johhansantana** [comment]
awesome! Happy new year as well and thank you for everything! Hopefully you can work things out with charity, that would be wonderful. Thank your time working on this! I'll be donating soon.

**Comment by Sly777** [comment]
thanks @johhansantana!
