### ISSUE TITLE
Choice of GraphQL client and project naming

### ISSUE THREAD

**Issue by sedubois** [Sly777/ran#53]
Is the reasoning behind choosing Apollo as GraphQL client explained somewhere? 

I guess Relay Modern is the obvious alternative, the only thing which isn't clear to me is its ability to support SSR, but should be feasible. [Ref](https://github.com/zeit/next.js/issues/1757#issuecomment-302443123), [ref](https://github.com/este/este/issues/1370#issue-238286079), [ref](https://github.com/este/este/blob/d0a31100b9fced823852498ff6d8e2d5701f633a/package.json#L49).

Whatever the case may be, my first reaction when seeing this project was being surprised that "Apollo" was part of its name. In the end, the choice of GraphQL client appears to me more like an "implementation detail". 

What probably matters more to the end-user is that RAN provides a GraphQL-first architecture out of the box. I think it would make more sense that the projects advertises itself as "React(-like) + GraphQL + Next.js" and reflects this in its name.

**Comment by Sly777** [comment]
Honestly, I read lots of stuff on Relay but I never use it on prod so I'm not sure to add it to ran. The reason for choosing Apollo was that It is good-documented, stable, easy-to-use and know how to deal with it. For the naming of ran, I just used "Apollo" word on it to create the word like "run" :)

But you right, maybe I should remove to show "apollo" on description to avoid to get mistake on meaning. Because, as you said, ran is "react+graphql+next.js" boilerplate.
