### ISSUE TITLE
ReasonReact sample page

### ISSUE THREAD

**Issue by Enalmada** [Sly777/ran#544]
[ReasonReact](https://reasonml.github.io/reason-react/) is probably the future of react.   Next.js has an [example](https://github.com/zeit/next.js/tree/canary/examples/with-reasonml) project for it.  It could benefit the community to have a single RAN page showing off some of the benefits (typesafe, immutable, reducers, etc built into language).  Easy to slowly migrate to Reason components ([link](https://reasonml.github.io/reason-react/docs/en/interop)).

**Comment by Sly777** [comment]
hmm, it's a really hard thing because I have no experience on Reason. Maybe we can write plugin system (I was talking about this on another issue: https://github.com/Sly777/ran/issues/24) that everyone can change the first structure of RAN with these plugins. So then someone can also prepare plugin of Reason for RAN :)

**Comment by Enalmada** [comment]
I have been thinking about this a bit more and since ReasonReact is still evolving so rapidly, it might make sense to have a generic "Next Steps" page at the end of the documentation describing things that people could consider doing but the RAN template has chosen not to implement.  Something like the [roadmap](https://www.rantoolkit.com/docs/Roadmap.html) page but with community suggestions and links of things that might be interesting to learn about but not quite RAN ready.
