### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by srghma** [Sly777/ran#89]
What about:
1. type checker (flow, ts)?
2. babel-plugin-root-import (finnaly made it, was hard, [but only with fork](https://github.com/BjornMelgaard/ran/blob/root-import/package.json#L92), [info](https://github.com/olalonde/eslint-import-resolver-babel-root-import/pull/6#issuecomment-320973956))
3. better folder structure (this is interesting):
3.1 move code to app
3.2.1 it can be like in https://github.com/scalable-react/scalable-react-typescript-boilerplate 
```
root -> app -> components/containers -> somename -> __tests__; index.js; styles.js; types.js; presentation.js (in contatiners also with actions, reducers, *.gql files and other)
```

3.2.2 oooooor ...  atoms, molecules, organisms, templates, theme like in https://github.com/devinit/datahub (I think its same as `components/containers` but with more graduality, but I dont know, I started learning next week ago)) ) 
4. jest, snapshots, stories
5. inferno, preact or react-lite in production (or everywhere) ?

**Comment by Sly777** [comment]
1 - Flow 👍 
2 - I couldn't find what's the benefit of this.
3 - I think Folder structure is enough for all-size projects but possibly If you have any suggestions, We can talk about that :)
4 - Jest 👍 
5 - I think It's not possible for now because of the next.js.

For some of your suggestions, I created issues each of them. I also tagged you so We can continue from there I think.

**Comment by BjornMelgaard** [comment]
2. its convenient
5. why? examples are broken? O_O

**Comment by BjornMelgaard** [comment]
next team is working to support typescript https://github.com/zeit/next.js/pull/2250 https://github.com/zeit/next.js/issues/2391
maybe better wait and use typescript instead of flow, @Sly777 , what you think?

cool typescript lib https://github.com/typestyle/typestyle
